- name: ___Installation de docker et ces dépendance___
  notify:
    - Installation des paquets systèmes requis
    - Ajout de Docker GPG apt Key
    - Ajout d'un Docker Repository
    - Installation de docker-ce et docker-compose
    - Installation du module docker pour python

- name: ___Création du fichier grafana___
  file:
    path: /home/"{{ grafana_username }}"/
    state: directory

- name: ___Copie des fichiers docker-compose___
  template:
      src: ./templates/grafana/docker-compose.yml.j2
      dest: /home/"{{ grafana_username }}"/grafana/docker-compose.yml
      mode: 0755

- name: ___Lancement du docker-compose___
  command: sudo docker-compose up -d
  args:
    chdir: /home/"{{ grafana_username }}"/grafana