- name: ___Installation de docker et ces dépendance___
  notify:
    - Installation des paquets systèmes requis
    - Ajout de Docker GPG apt Key
    - Ajout d'un Docker Repository
    - Installation de docker-ce et docker-compose
    - Installation du module docker pour python
  
- name: ___Création du fichier DATABASE_USERS dans le home directory___
  file:
    path: /home/"{{ mysql_username }}"/database_users
    state: directory

- name: ___Création du fichier MYSQL dans le home directory___
  file:
    path: /home/"{{ mysql_username }}"/mysql
    state: directory
  
- name: ___copie du fichier docker-compose___
  template:
    src: ./templates/mysql/docker-compose.yml.j2
    dest: /home/"{{ mysql_username }}"/mysql/docker-compose.yml
    owner: "{{ mysql_username }}"
    group: "{{ mysql_username }}"
    mode: 0644

- name: ___copie du fichier databases.sql___
  template:
    src: ./templates/mysql/databases.sql.j2
    dest: /home/"{{mysql_username}}"/database_users/databases.sql
    owner: "{{ mysql_username }}"
    group: "{{ mysql_username }}"
    mode: 0644

- name: ___Lancement du docker-compose___
  command: sudo docker-compose up -d
  args:
    chdir: /home/"{{ mysql_username }}"/mysql