- name: ___Installation de docker et ces dépendance___
  notify:
    - Installation des paquets systèmes requis
    - Ajout de Docker GPG apt Key
    - Ajout d'un Docker Repository
    - Installation de docker-ce et docker-compose
    - Installation du module docker pour python

- name: ___Création du fichier prometheus dans le home directory___
  file:
    path: /home/"{{ prometheus_username }}"/prometheus
    state: directory

- name: ___Copie du fichiers prometheus en yaml___
  template:
    src: ./templates/prometheus/prometheus.yml.j2
    dest: /home/"{{ prometheus_username }}"/prometheus/prometheus.yml
    mode: 0755

- name: ___Copie du fichiers docker-compose___
  template:
    src: ./templates/prometheus/docker-compose.yml.j2
    dest: /home/"{{ prometheus_username }}"/prometheus/docker-compose.yml
    mode: 0755

- name: ___Lancement du docker-compose___
  command: sudo docker-compose up -d
  args:
    chdir: /home/"{{ prometheus_username }}"/prometheus