---

- name: Déployement de docker, Prometheus et grafana
  hosts: db
  become: true

  tasks:
   - name: Installation des paquets systèmes requis
     apt:
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common
         - python3-pip
         - virtualenv
         - python3-setuptools
         - PyYAML 
       state: latest
       update_cache: true

   - name: Add Docker GPG apt Key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Ajout d'un Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

   - name: Installation de docker-ce et docker-compose
     apt:
       name:
         - docker-ce
         - docker-compose
       state: latest
       update_cache: true

   - name: Installation du module docker pour python
     pip:
       name: docker

   - name: Copie du dossier ./prometheus vers /monitoring/prometheus
     copy:
        src: ./prometheus
        dest: /monitoring/prometheus
        mode: 0755

   - name: Déployer l'infrastructure prometheus/grafana
     docker_stack:
      state: present
      name: monitoring
      compose:
        - /monitoring/prometheus/docker-compose.yml
