- name: Installation des paquets systèmes requis
  apt:
     name:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - python3-pip
       - virtualenv
       - python3-setuptools 
     state: latest
     update_cache: true

- name: Création de différents fichiers
  file:
    path: /home/debian/grafana/volume
    state: directory

- name: Copie des fichiers docker-compose
  copy:
      src: ./grafana/docker-compose.yml
      dest: /home/debian/grafana/docker-compose.yml
      mode: 0755
      
- name: Lancement du docker-compose
  command: docker-compose up -d # très important -d !!
  args:
    chdir: /home/debian/grafana # Mettre la direction ou se trouve le docker-compose