#global:
#  scrape_interval: 1m
#
#scrape_configs:
#  - job_name: 'prometheus'
#    scrape_interval: 1m
#    static_configs:
#      - targets: ['localhost:9090']
#
#  - job_name: 'node'
#    static_configs:
#      - targets: ['137.74.106.194:9090']
#        labels: 
#          host: 'formation'
#          group: 'formation' 
#
#remote_write:
#  - url: 'control.somily.fr'
#    basic_auth:
#      username: 'nicodevopsfr'
#      password: 'eyJrIjoiZTk3azVnaTM2ZHI5cFdndDJTWms5Z3dyWDdJMXY5bGoiLCJuIjoiUHJvamV0X2ZpbF9yb3VnZSIsImlkIjoxfQ=='
#
#

#global:
#  scrape_interval: 1m
#
#scrape_configs:
#  - job_name: 'remote_server_metrics'
#    scrape_interval: 10s
#    metrics_path: '/metrics'
#    scheme: 'http'
#    static_configs:
#      - targets: ['217.182.205.43:9100']

global:
  scrape_interval:     15s
  evaluation_interval: 15s

#scrape_configs:
#  - job_name: 'wordpress_metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['217.182.205.43:9100']

scrape_configs:
  - job_name: 'wordpress'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['217.182.205.43:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_compose_service]
        action: replace
        target_label: job
      - source_labels: [__meta_docker_compose_service]
        regex: "(.+)"
        target_label: service
        replacement: "$1"
      - source_labels: [__meta_docker_compose_container_label_com_docker_compose_project]
        target_label: project

  - job_name: 'git'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['141.94.6.208:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_docker_compose_service]
        action: replace
        target_label: job
      - source_labels: [__meta_docker_compose_service]
        regex: "(.+)"
        target_label: service
        replacement: "$1"
      - source_labels: [__meta_docker_compose_container_label_com_docker_compose_project]
        target_label: project