version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    #restart: unless-stopped
    volumes:
      - /home/"{{ prometheus_username }}"/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      #- /home/formation/prometheus/volume/:/prometheus
